#!/bin/bash

# РЕШЕНИЕ ПРОБЛЕМ ПОСЛЕ ДЕПЛОЯ

echo "🔧 Исправление проблем винтажного магазина..."

echo ""
echo "1. 🔍 ПРОВЕРКА БЕЛОГО ЭКРАНА В БРАУЗЕРЕ:"
echo ""
echo "# Проверьте API работает ли:"
echo "curl http://185.177.216.22/api/products"
echo ""
echo "# Проверьте логи приложения:"
echo "sudo journalctl -u vintage-shop -n 20"
echo ""
echo "# Проверьте JavaScript ошибки в браузере:"
echo "# 1. Откройте http://185.177.216.22"
echo "# 2. Нажмите F12 → Console"
echo "# 3. Посмотрите ошибки"

echo ""
echo "2. 📱 ПРАВИЛЬНАЯ НАСТРОЙКА BOTFATHER:"
echo ""
echo "Вариант A - Через Menu Button:"
echo "/mybots"
echo "# Выберите вашего бота"
echo "# Bot Settings → Menu Button → Set Menu Button"
echo "# Текст: 🛍 Открыть магазин"
echo "# URL: http://185.177.216.22"
echo ""
echo "Вариант B - Через WebApp:"
echo "/newapp"
echo "# Выберите бота"
echo "# Название: Vintage Shop"
echo "# Description: Винтажный магазин"
echo "# Photo: загрузите картинку магазина"
echo "# Web App URL: http://185.177.216.22"
echo ""
echo "Вариант C - Через команды:"
echo "/setcommands"
echo "# Выберите вашего бота"
echo "# Добавьте команды:"
echo "# start - Запустить магазин"
echo "# shop - Открыть каталог"

echo ""
echo "3. 🛠️ КОМАНДЫ ДЛЯ ОТЛАДКИ:"
echo ""
echo "# Проверка работы API:"
echo "curl http://185.177.216.22/health"
echo "curl http://185.177.216.22/api/products"
echo ""
echo "# Проверка логов:"
echo "sudo journalctl -u vintage-shop -f"
echo ""
echo "# Перезапуск если нужно:"
echo "sudo systemctl restart vintage-shop"
echo "sudo systemctl restart nginx"
echo ""
echo "# Проверка статуса:"
echo "sudo systemctl status vintage-shop"
echo "sudo systemctl status nginx"

echo ""
echo "4. 🔧 ВОЗМОЖНЫЕ РЕШЕНИЯ БЕЛОГО ЭКРАНА:"
echo ""
echo "# Если API не отвечает, проверьте CORS:"
echo "curl -H 'Origin: http://185.177.216.22' http://185.177.216.22/api/products"
echo ""
echo "# Пересборка фронтенда:"
echo "cd /var/www/my-vintage-shop/frontend"
echo "npm run build"
echo "sudo systemctl restart vintage-shop"
echo ""
echo "# Проверка что файлы собрались:"
echo "ls -la /var/www/my-vintage-shop/frontend/dist/"

echo ""
echo "5. 📋 ПОСЛЕДОВАТЕЛЬНОСТЬ ДИАГНОСТИКИ:"
echo "1. Откройте сайт в браузере: http://185.177.216.22"
echo "2. Нажмите F12 → Console"
echo "3. Обновите страницу (Ctrl+F5)"
echo "4. Скопируйте все ошибки из консоли"
echo "5. Проверьте Network вкладку - какие запросы падают"
echo ""
echo "✅ После исправления протестируйте в Telegram!"